### ISSUE TITLE
Refactor template

### ISSUE THREAD

**Issue by akashdp3** [akashdp3/turbo-tauri-next-template#1]
### To-Do

- [ ] Move `typescript-config` and `eslint-config` to toolings folder and include `toolings/*` in `pnpm-workspace.yaml`.
- [ ] Use `typescript-config` and `eslint-config` in `apps/desktop`
- [ ] Add `daemon` as `false` in `turbo.json` once the issue is fixed
    - Update: No need to disable `daemon`. It can be fixed setting `ui` to `stream` in `turbo.json`
- [ ] Remove `apps/web`.
